# Generated by Django 3.2.12 on 2022-04-04 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='users',
            new_name='user',
        ),
    ]
