# Generated by Django 3.2.12 on 2022-05-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='accepted',
            field=models.BooleanField(null=True),
        ),
    ]
