# Generated by Django 3.2.12 on 2022-04-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_profile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='personal_info',
            field=models.TextField(null=True),
        ),
    ]
