# Generated by Django 3.2.12 on 2022-04-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_event_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='random_avatar.jpg', upload_to='avatars'),
        ),
    ]
