# Generated by Django 3.2.12 on 2022-04-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='personal_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
