# Generated by Django 3.2.12 on 2022-05-10 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0008_alter_comment_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ManyToManyField(null=True, related_name='user_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
