# Generated by Django 3.2.12 on 2022-04-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_profile_personal_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='random.jpg', upload_to='static/images'),
        ),
    ]
