# Generated by Django 3.2.13 on 2022-06-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20220627_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.AddField(
            model_name='profile',
            name='friendship',
            field=models.ManyToManyField(blank=True, related_name='friends', through='Home.Friendship', to='Home.Profile'),
        ),
    ]
