# Generated by Django 3.2.13 on 2022-06-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20220627_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='static/avatars/random_avatar.jpg', upload_to='avatars'),
        ),
    ]
